package humaxdigital.joycast.codec.request;

import java.util.ArrayList;
import java.util.List;

import humaxdigital.joycast.codec.response.Param;

/**
 * Request is abstraction to describe request message which is sent to server
 * We refer to { @link http://www.mkyong.com/java/jackson-2-convert-java-object-to-from-json/ }
 * to encode/decode JSON string on JAVA
 * Please note reference having examples of jackson-2-library to parse json easily
 */
public class Request 
{
    /**
     * Constructor without any parameter is called only when Event is created
     */
    public Request() 
    {
        m_header = new Header();
        m_body = new Body();
    }
    
    /**
     * Constructor with parameters is called when object from Request is created in controller
     * @param controller_id id of controller generated by Server
     * @param controller_type type of controller Server supporting
     */
    public Request(String controller_id, String controller_type) 
    {
        m_header = new Header();
        m_body = new Body();
        
        m_header.setControllerId(controller_id);
        m_header.setControllerType(controller_type);
        
        setHeader(m_header);
    }
    
    /**
     * Class to describe Header field in Request message and to include id and type of controller
     * which server can support 
     */
    public static class Header 
    {
        public void setControllerId(String controller_id) 
        {
            m_controller_id = controller_id;
        }
        
        public String getControllerId() 
        {
            return m_controller_id;
        }
        
        public void setControllerType(String controller_type) 
        {
            m_controller_type = controller_type;
        }
        
        public String getControllerType() 
        {
            return m_controller_type;
        }
            
        protected String m_controller_id;
        protected String m_controller_type;
    }
    
    /**
     * Class to describe Body field in Request message
     */
    public static class Body 
    {
        public String getHash() 
        {
            return m_hash;
        }
        
        public void setHash(String hash) 
        {
            m_hash = hash;
        }
        
        public String getActionName() 
        {
            return m_action_name;
        }
        
        public void setActionName(String action_name) 
        {
            m_action_name = action_name;
        }
        
        public String getActionType() 
        {
            return m_action_type;
        }
        
        public void setActionType(String action_type) 
        {
            m_action_type = action_type;
        }
        
        public List<Param> getParamList() 
        {
            return m_params;
        }
        
        public void setParamList(List<Param> params) 
        {
            m_params = params;
        }
        
        protected String m_hash;
        protected String m_action_name;
        protected String m_action_type;
        protected List<Param> m_params = new ArrayList<Param>();
    }
    
    public Header getHeader() 
    {
        return m_header;
    }
    
    public void setHeader(Header header) 
    {
        m_header = header;
    }
    
    public Body getBody()
    {
        return m_body;
    }
    
    public void setBody(Body body) 
    {
        m_body = body;
    }
    
    protected Header m_header = new Header();
    protected Body m_body = new Body();
    
    public static final String REQUEST = "request";
}
